Require docutils.
Fixes;
```
ERROR: Complete output from command python setup.py egg_info:
ERROR: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pip-install-vcb4byda/sphinxcontrib-domaintools/setup.py", line 11, in <module>
    import domaintools
  File "sphinxcontrib/domaintools.py", line 25, in <module>
    from docutils import nodes
ModuleNotFoundError: No module named 'docutils'
```